// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Bookmark struct {
	ID          int64     `json:"id"`
	Url         string    `json:"url"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	Summary     *string   `json:"summary"`
	SourceType  string    `json:"source_type"`
	FaviconUrl  *string   `json:"favicon_url"`
	ImageUrl    *string   `json:"image_url"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type BookmarkCollection struct {
	BookmarkID   int64 `json:"bookmark_id"`
	CollectionID int64 `json:"collection_id"`
}

type BookmarkTag struct {
	BookmarkID int64 `json:"bookmark_id"`
	TagID      int64 `json:"tag_id"`
}

type BookmarksFt struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Summary     string `json:"summary"`
}

type Collection struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Icon        *string   `json:"icon"`
	CreatedAt   time.Time `json:"created_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type Tag struct {
	ID    int64   `json:"id"`
	Name  string  `json:"name"`
	Color *string `json:"color"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
